apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
  namespace: 3-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-cont
        image: zahramurtaza/app-backend-tier:latest
        ports:
        - containerPort: 3200
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: user
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
      resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"


