apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: 3-tier-app
spec:
  volumeName: app-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
